'\" t
.\"     Title: grits-demo
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.77.1 <http://docbook.sf.net/>
.\"      Date: 01/20/2013
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "GRITS\-DEMO" "1" "01/20/2013" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
grits-demo \- Grits demonstration program
.SH "SYNOPSIS"
.HP \w'\fBgrits\-demo\ [GTK_OPTIONS]\fR\ 'u
\fBgrits\-demo [GTK_OPTIONS]\fR
.SH "DESCRIPTION"
.PP
\fBgrits\-demo\fR
TODO (short description)
.PP
TODO (long description)
.SH "ENVIRONMENT"
.PP
GRITS_PLUGIN_PATH
.RS 4
Secondary path to use when searching for plugins\&.
.RE
.SH "FILES"
.PP
$HOME/\&.config/grits/config\&.ini
.RS 4
Configuration file used to store loaded plugins and a few other settings\&.
.RE
